### ISSUE TITLE
Task for integratej2objc

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#14]
Do you have plans or are you working on a task for integrating 

https://github.com/developertown/integratej2objc

This would match perfectly with the plugin.

**Comment by jonnolen** [comment]
We are already working through it!

**Comment by confile** [comment]
Great. Looking forward to test it.

**Comment by brunobowden** [comment]
Hi Guys,
I'm being pulled in to some other work for the next week or so. Happy to
look at pull requests, e.g. for integratej2objc but I won't be able to work
on it directly myself.

**Comment by confile** [comment]
@jonnolen Did you make any progress on this issue?

**Comment by confile** [comment]
@jonnolen @brunobowden I created a pull request solving this issue. 

https://github.com/brunobowden/j2objc-gradle/pull/19

**Comment by confile** [comment]
@brunobowden integratej2objc still has the issue of not removing an old linked folder, it generates a new folder on every execution. Are you able to fix that? 
(https://github.com/developertown/integratej2objc/issues/2)

**Comment by formvoltron** [comment]
I'm I hitting this issue?

I'm trying to run
gradle --stacktrace j2objcXcode

I get this error:
Deleting destDir to fill with generated objc files... /Users/mattpease/IdeaProjects/MyApplicationCleanCode/app/j2objc-generated
:app:j2objcXcode FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:j2objcXcode'.
> A problem occurred starting process 'command 'integratej2objc''

Caused by: java.io.IOException: Cannot run program "integratej2objc" (in directory "/Users/mattpease/IdeaProjects/MyApplicationCleanCode/app"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 4 more



I setup these settings in the j2objc.gradle file.  


    // LINK
    // directory of the target Xcode project
    String xcodeProjectDir = "/Users/mattpease/Documents/basic"
    // J2objc generated files are copied here, relative path to xcodeProjectDir
    // Directory contents will be deleted on every execution of the link command
    String xcodeJ2objcGeneratedDir = "j2objc-generated"
    // Xcode target the generated files should be linked to
    String xcodeTarget = "basicJava"
    // name of the target Xcode project, e.g., MyProject.xcodeproj
    String xcodeProject = "basic.xcodeproj"

**Comment by confile** [comment]
@formvoltron did you install integratej2objc?

**Comment by formvoltron** [comment]
no. But now I see it's a separate project. @brunobowden if you don't add the integratej2objc target, I think it would help to just mention it on the project page.  

@confile your project description here seems to have the wrong format for the gem file:

This seems to work:
gem 'integratej2objc', :git => 'https://github.com/developertown/integratej2objc.git'

I don't see a way to create an issue for your project.

**Comment by formvoltron** [comment]
@confile  I'm having trouble getting integratej2objc going.  Can you help?


air-2:app mattpease$ sudo gem install xcodeproj
Successfully installed xcodeproj-0.23.1
Parsing documentation for xcodeproj-0.23.1
1 gem installed

air-2:app mattpease$ sudo gem install thor
Successfully installed thor-0.19.1
Parsing documentation for thor-0.19.1
1 gem installed

My Gemfile:
gem 'integratej2objc', :git => 'https://github.com/developertown/integratej2objc.git'


air-2:app mattpease$ bundle install
Updating https://github.com/developertown/integratej2objc.git
Could not find gem 'xcodeproj (= 0.23) ruby' in the gems available on this machine.

fail.

any tips?  Thank you

**Comment by confile** [comment]
@formvoltron Use bundler: 

Currently the gem is not deployed to rubygems. The best way I've found to use it locally is with bundler

Gemfile entry:

gem 'integratej2objc', git:'https://github.com/developertown/integratej2objc.git'
bundle; bundle exec integratej2objc help;

**Comment by formvoltron** [comment]
@confile  Yes I followed those instructions.. those are failing for me.

I created an issue over at the main integratej2objc project.  https://github.com/developertown/integratej2objc/issues/15  

So frustrating.. I just want to build some very simple "hello world" type java and use it in Xcode.

**Comment by brunobowden** [comment]
@jonnolen, @developertown

It would be great to get the integratej2objc tool in good shape and make it easy to install - I presume by making it a Rubygem. J2objc is coming up to doing a 1.0 release and it would be best if all these tools are ready for that at the same time.

Issue to make it a RubyGem:
https://github.com/developertown/integratej2objc/issues/3

I am changing the j2objc.gradle script to identify when integratej2objc is not installed so it can explain how to install the tool. This is all part of making it much easier to use so we can avoid lots of support questions. I've successfully installed integratej2objc and it's now working for me but I had to adapt j2objc.gradle to use bundle instead. The install isn't straight forward and the instructions on the GitHub page didn't work for me:

https://github.com/developertown/integratej2objc/#installation

These steps worked for me instead:

    $ sudo gem install bundler
    Password:
    Successfully installed bundler-1.9.3
    Parsing documentation for bundler-1.9.3
    1 gem installed
    $ echo "gem 'integratej2objc', git:'https://github.com/developertown/integratej2objc.git'" >> Gemfile
    $ bundle
    <REMOVED>
    Using integratej2objc 0.0.1 from https://github.com/developertown/integratej2objc.git (at master)
    Using bundler 1.9.3
    Bundle complete! 1 Gemfile dependency, 11 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.
    $ bundle exec integratej2objc help
    Commands:
      integratej2objc help [COMMAND]                                                                                                                               ...
      integratej2objc integrate_source -g, --group=GROUP -p, --project-root=PROJECT_ROOT -s, --source-root=SOURCE_ROOT -t, --target=TARGET -x, --xcodeproj=XCODEPRO...

**Comment by formvoltron** [comment]
Thanks @brunobowden   I've done the same as you, but I still get that error running

gradle j2objcXcode

Caused by: java.io.IOException: Cannot run program "integratej2objc" (in directory "/Users/mattpease/IdeaProjects/MyApplicationCleanCode/app"): error=2, No such file or directory

But I suppose that is what this issue is about.  task for integratej2objc  is on the TODO.

**Comment by brunobowden** [comment]
I have a fix for that - I'll publish it later today

**Comment by formvoltron** [comment]
Thank you, but no need to rush it for me.  I ran the direct integratej2objc command, but all that seems to do is add the files to Xcode, nothing more?

That's not what I was hoping for.   I was hoping I could be lazy & skip all the linker & include path setup.  I guess not.  I'll use the j2reversi project as an example of what to link to & how to do that.

Thanks for the gradle plugin.  Very nice not to have to download & manage jar dependencies.

**Comment by confile** [comment]
@brunobowden where do you publish the fix?

**Comment by brunobowden** [comment]
Shared PR just now. I'd like to see this as a RubyGem with an easy install.

**Comment by confile** [comment]
@brunobowden Okay looking forward to see it working. Please keep in mind that there is still this annoying [issue: generated folder is not removed when integrating code a second time.](https://github.com/developertown/integratej2objc/issues/2)

**Comment by confile** [comment]
This is not relevant anymore.
