### ISSUE TITLE
Cycle Finder Task

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#3]
I created a cycle Finder Task: 

```
class J2objcCycleFinderTask extends DefaultTask {
	
	@InputFiles FileCollection srcFiles
	@OutputFile File destFile
	
	@TaskAction
	def start() {

		println "Start"
		
        def isWindows = J2objcUtils.isWindows()
        def j2objcHome = J2objcUtils.j2objcHome(getProject())
        def cycleFinderExec = j2objcHome + "/cycle_finder"
        def firstArgs = ""
        if (isWindows) {
            j2objcExec = "java"
            // "-Xbootclasspath:${j2objcHome}/lib/jre_emul.jar"
            firstArgs = "-jar ${j2objcHome}/lib/cycle_finder.jar"
        }

		// clear the destFile
		project.delete destFile
		
        srcFiles = J2objcUtils.fileFilter(srcFiles,
                project.j2objcConfig.translateIncludeRegex,
                project.j2objcConfig.translateExcludeRegex)

        if (project.j2objcConfig.filenameCollisionCheck) {
            J2objcUtils.filenameCollisionCheck(srcFiles)
        }

		print "cycleFinderExec: "+cycleFinderExec
		

//		def stdout = new ByteArrayOutputStream()
        project.exec {
            executable cycleFinderExec
			
//                args firstArgs.split()

            args "-sourcepath", project.file("src/main/java").path

            project.j2objcConfig.translateJ2objcLibs.each { library ->
                def libPath = J2objcUtils.j2objcHome(getProject()) + "/lib/" + library
                args "-classpath", project.file(libPath).path
            }

//                args "${project.j2objcConfig.translateFlags}".split()

            srcFiles.each { file ->
                args file.path
            }
			
			standardOutput = stdout
			destFile << stdout
        }
		
	}
	
}
```

and append in ``class j2objc implements Plugin<Project>``:

```
			tasks.create(name: "j2objcCycleFinder", type: J2objcCycleFinderTask) {
				description "Run the cycle_finder tool on all Java source files"
				outputs.upToDateWhen { false }	// make the task run on every execution
				srcFiles = files(
					fileTree(dir: projectDir,
							include: "**/*.java",
							exclude: project.relativePath(buildDir)))
				destFile = file("${buildDir}/j2objc_cycleFinderResult")
			}
```

The command is executed correctly but the task fails. May be this helps you. It was designed to write the output in the ``destFile`` so one can see the printout of the cycle finder.

**Comment by brunobowden** [comment]
Thanks @confile, this is very helpful. I've got the basic parts of this working. I want to work through eliminating the cycles in my own project, then I'll push the changes publicly. It found a lot more cycles that I expected but they appear to all be in third party code.

One of the changes I've made it to send the output to stdout instead of a file... for example if it fails on a build machine, it's important that stdout has the output incase you can't access the file directly.

**Comment by confile** [comment]
@brunobowden Well as you have sen in my post on google groups I found 31 cycles where no cycles are. Also they are in third party libs. 

Your idea to send the output to the console seems reasonable.

**Comment by brunobowden** [comment]
I want to get some feedback from Tom before pushing this live. I think I
might disable it by default as it may be intimidating for initial users...
or at least have a whitelist for the standard loops to ignore.

**Comment by confile** [comment]
Great I am looking forward to see it.

**Comment by brunobowden** [comment]
Fixed in latest push

**Comment by confile** [comment]
+1 I will test it. Thanks for your work.

**Comment by confile** [comment]
@brunobowden I am struggling using your cycle finder. Could you please post a sample config for it. 

I tried: 

```
j2objcConfig {
   ...

	cycleFinder = true
	cycleFinderFlags (
		--sourcefilelist $ {projectDir})
}
```
but it did not work. Could you also please publish your jre whitelist?

Thank you.

**Comment by confile** [comment]
Here is the error I get: 

```
* Where:
Build file '/Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/build.gradle' line: 123

* What went wrong:
Could not compile build file '/Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/build.gradle'.
> startup failed:
  build file '/Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/build.gradle': 123: unexpected token:  @ line 123, column 33.
     	cycleFinderFlags ("-whitelist" "${J2ObjcSource}/jre_emul/cycle_whitelist.txt" "--sourcefilelist" "${J2ObjcSource}/jre_emul/build_result/java_sources.mf")
                                     ^
  
  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by brunobowden** [comment]
cycleFinderFlags is simply a string, not an array. Also it's
--whitelist and not a single "-". I've fixed the comments for that.

Correction:

cycleFinderFlags ("--whitelist
${J2ObjcSource}/jre_emul/cycle_whitelist.txt --sourcefilelist
${J2ObjcSource}/jre_emul/build_result/java_sources.mf")

**Comment by confile** [comment]
Great it work fine thank you Bruno.

**Comment by brunobowden** [comment]
I appreciate your help testing.

I'm going to get Dagger working as well and then email j2objc-discuss, so
please hold back publicizing it just yet.

**Comment by confile** [comment]
Okay.
