### ISSUE TITLE
J2objcXcodeTask: Failed to execute

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#37]
I recently updated to the latest version of the J2objcXcodeTask and got the following error while running ``gradle j2objcXcode --info``:

```
Executing task ':j2objcXcode' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'bundle''. Working directory: /Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/test-core Command: bundle exec integratej2objc integrate_source -p /Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/test-core/../Test -x Test.xcodeproj -s ../test-core/build/j2objc -g j2objc-generated -t Test
Successfully started process 'command 'bundle''
Could not locate Gemfile or .bundle/ directory
:j2objcXcode FAILED
:j2objcXcode (Thread[main,5,main]) completed. Took 0.198 secs.
```

When I replace: 

```
                executable "bundle"

                args "exec"
                args "integratej2objc"
                args "integrate_source"
                args "-p", "${xcodeProjectDir}"
                args "-x", "${xcodeProject}"
                args "-s", "${srcFolder}"
                args "-g", "${xcodeJ2objcGeneratedDir}"
                args "-t", "${xcodeTarget}"
```
with
```
                executable "integratej2objc"
                args "integrate_source"
                args "-p", "${xcodeProjectDir}"
                args "-x", "${xcodeProject}"
                args "-s", "${srcFolder}"
                args "-g", "${xcodeJ2objcGeneratedDir}"
                args "-t", "${xcodeTarget}"
```
It worked without problems.

**Comment by brunobowden** [comment]
There's a couple of ways to install integratej2objc as that's what's
causing the issue. I had the other method fail for other people, so I did
that fix.

Try doing the bundle install and seeing if that works for you then:
https://github.com/developertown/integratej2objc#installation

**Comment by confile** [comment]
I did installation with bundle. Did not work this way.

**Comment by confile** [comment]
@brunobowden Bruno I still have the problem that when using the Xcode task the generated folder generated on each task execution. It should be removed and then generated. Are you able to fix this?

**Comment by confile** [comment]
@brunobowden We should mark this J2objcXcodeTask as deprecated.

**Comment by brunobowden** [comment]
Let's talk about this on June 2nd

**Comment by confile** [comment]
What is on June 2nd?

**Comment by advayDev1** [comment]
can we close this won't fix? @brunobowden

**Comment by brunobowden** [comment]
won't fix => working instead on new version with CocoaPods
