### ISSUE TITLE
Dagger2 with J2Objc

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#4]
Did you make any progress on using Dagger2 with J2Objc?

I created a demo with made it work with GWT: https://github.com/confile/GWT-Dagger2-Demo

**Comment by brunobowden** [comment]
Just finished getting Guava integrated and working. Inject is now added.
Now going through the dagger 2 examples. Hopefully I'll get something up
and running tomorrow. Also thanks for sharing your own demo.

**Comment by confile** [comment]
Just look at my example project it will save you a lot of time. 

The only thing which is missing is adding the dagger2 jar to J2Objc. This must be done via classpath. I did not understood how to add multiple jars to the classpath using your gradle plugin. 

If you did this I would be happy if you could post it to me. 

Here you can see how to configure your  [build.gradle][1]  for dagger2.

Here is a simple dagger [example][2]  you can copy and paste. Use it like this: 

```
MyWidgetGinjector injector = Dagger_MyWidgetGinjector.create();
SomeService service = injector.getSomeService();
```

Hope this helps!

  [1]: https://github.com/confile/Gradle-MultiProject-Test/blob/master/First/build.gradle
[2]: https://github.com/confile/GWT-Dagger2-Demo/tree/master/src/test/client/test2

**Comment by confile** [comment]
I manage to translate a simple project which included dagger2. Using ``javac`` and ``j2objc`` worked fine even with the generated classes from the Dagger Components. I mean the ``Dagger_....java`` files.

 I created this pull request: https://github.com/brunobowden/j2objc-gradle/pull/10 so you can specify the source path of the annotation processor output.  

Here is the configuration I use: 

```
	translateFlags """--no-package-directories --prefixes prefixes.properties --mapping method-mappings.properties -use-arc -classpath ${projectDir}/lib/dagger-2.0-SNAPSHOT.jar"""
```

My generated files in ``build/source/apt`` are: 

```
Dagger_MyWidgetGinjector.java
MyWidgetClientModule$$ProvideSomeServiceFactory.java
```
(Based on this project: https://github.com/confile/GWT-Dagger2-Demo)

Here is what I get while doing the translation: 

```
error: /Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/build/source/apt/com/example/incrementer/shared/test2/Dagger_MyWidgetGinjector.java:26: MyWidgetClientModule$$ProvideSomeServiceFactory cannot be resolved to a type
translating /Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/build/source/apt/com/example/incrementer/shared/test2/MyWidgetClientModule$$ProvideSomeServiceFactory.java
Translated 8 files: 1 errors, 0 warnings
```

Do you have any idea what to do here? Thank for your help.

**Comment by confile** [comment]
I should post my command line compile command as well. The following works perfect: 

```
javac -d build/classes -sourcepath src/main/java:build/source/apt src/main/java/com/example/incrementer/shared/SomeEvent.java src/main/java/com/example/incrementer/shared/NumberIncrementer.java src/main/java/com/example/incrementer/shared/JSNIExample.java src/main/java/com/example/incrementer/shared/test2/SomeService.java src/main/java/com/example/incrementer/shared/test2/SomeServiceImpl.java src/main/java/com/example/incrementer/shared/test2/MyWidgetClientModule.java src/main/java/com/example/incrementer/shared/test2/MyWidgetGinjector.java build/source/apt/com/example/incrementer/shared/test2/Dagger_MyWidgetGinjector.java -classpath lib/dagger-2.0-SNAPSHOT.jar:lib/javax.inject-1.jar
```
 The generated file  ``MyWidgetClientModule$$ProvideSomeServiceFactory.java`` is also compiled although I did not explicitly call ed it in the javac command. When I put this file in the javac classpath then I get an error 

``
javac: file not found: build/source/apt/com/example/incrementer/shared/test2/MyWidgetClientModule55781ProvideSomeServiceFactory.java
``

I guess this is because of you $ sign. May be this causes you plugin to fail to translate too?

**Comment by confile** [comment]
@brunobowden Did you make any progress on this issue?

**Comment by jonnolen** [comment]
I haven't done any additional work on this gem, and have no immediate
plans.  We have ended up abandoning j2objc for our current project.

**Comment by confile** [comment]
And what about you @brunobowden ?

**Comment by brunobowden** [comment]
Hi @confile. I'm busy with some higher priority work right now and
attending the TED conference next week. I'll likely to return to this after
that, in about two weeks tiem.

**Comment by confile** [comment]
@brunobowden Hi Bruno, did you make any progress o this issue?

**Comment by confile** [comment]
@brunobowden This is a j2objc issue see https://github.com/google/j2objc/issues/510#issuecomment-89437397

**Comment by confile** [comment]
I reopened this issue because translation still raises error. See https://github.com/google/j2objc/issues/513

**Comment by confile** [comment]
@brunobowden I still struggling with this issue and I need help. Translating dagger and linking to Xcode works fine using the following configuration: 

```
translateFlags """--no-package-directories --prefixes prefixes.properties -use-arc --doc-comments --build-closure
		-classpath ${projectDir}/lib/auto-factory-0.1-beta1.jar:${projectDir}/lib/auto-service-1.0-rc1.jar:${projectDir}/lib/guava-16.0.jar:${projectDir}/lib/javawriter-2.4.0.jar:${projectDir}/lib/dagger-1.2.0.jar"""
	
translateSourcepaths "${projectDir}/libSrc/javax.inject-1-sources.jar:${projectDir}/libSrc/dagger-2.0-SNAPSHOT-sources.jar"
```

The only problem is that transpiling gives the following warning: 
```
warning: could not find source path for dagger.Provides.Type
```
If I linke my translated files with Xcode I get the following compiler error: 

```
clang: error: no such file or directory: '/Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/build/j2objc/ApplicationModule$ProvideSomeClassXFactory.m'
clang: error: no input files
```
If I do not use the ``@Provides`` annotation from dagger2 I can build in Xcode without problems. 

Here is the code I use: 

```
package com.example;

import javax.inject.Singleton;

import dagger.Module;
import dagger.Provides;




@Module
public class ApplicationModule {

	@Provides
	@Singleton
	SomeClassX provideSomeClassX() {
		return new SomeClassX();
	}
}
```
and
```
package com.example;

import dagger.Provides;

public class SomeClassX {
}
```

If you could solve this last part of the puzzle, then we are done.

**Comment by confile** [comment]
Here is the latest open issue: https://github.com/google/j2objc/issues/517

**Comment by brunobowden** [comment]
@confile - excellent writeup on the bug, thanks for taking the time to do
that properly

**Comment by confile** [comment]
@brunobowden Well I would need a little help on this issue.

**Comment by confile** [comment]
@brunobowden How do you deal with java files generated with annotation processor which contains $$

**Comment by confile** [comment]
@brunobowden This is fixed with my latest pull request.
