### ISSUE TITLE
Switch from IntegrateJ2objc to CocoaPods?

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#44]
Should we do the shift from IntegrateJ2objc to [CocoaPods](https://cocoapods.org)?

**Comment by brunobowden** [comment]
Agreed on making it easy and that sounds a likely path. What was
integratej2objc a fork of?

**Comment by confile** [comment]
This is integratej2objc:
https://github.com/developertown/integratej2objc

**Comment by confile** [comment]
done see: 

https://github.com/brunobowden/j2objc-gradle/pull/46
