### ISSUE TITLE
CycleFinderMaxCycles setting to fail build when more cycles found

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#5]
Cycle Finder Task Exit with Failure. I am not sure if this is fixable, but so far I had the same problem when I created the cycle finder task.

Works correct but gives a Failure output.
```
BUILD SUCCESSFUL

Total time: 3.293 secs
http-server:TestJ2Objc mg$ gradle j2objcCycleFinder
:addAptCompilerArgs
:compileJava
:processResources UP-TO-DATE
:classes
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:j2objcCycleFinder

***** Found reference cycle *****
NumberIncrementer -> (field x with type JSNIExample)
JSNIExample -> (field x with type NumberIncrementer)
----- Full Types -----
Lcom/example/incrementer/shared/NumberIncrementer;
Lcom/example/incrementer/shared/JSNIExample;

1 CYCLES FOUND.
:j2objcCycleFinder FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/j2objc.gradle' line: 277

* What went wrong:
Execution failed for task ':j2objcCycleFinder'.
> Process 'command '/Applications/J2Objc/j2objc-0.9.6/cycle_finder'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.552 secs

```

**Comment by brunobowden** [comment]
It's designed to fail in this way. If you enable cycleFinder and it finds a
cycle, it will fail the build. My code currently runs clean with no cycles,
so I want it to alert on all new cycles.

What I'll do is add a "cycleFinderMaxCycles" integer value, that in this
case you could set to 1. So the build will work if there's only one cycle,
then fail if a new cycle is added (that's what you want to know about).

**Comment by brunobowden** [comment]
See this code for "testExecutedCheck" which has similar logic, happy to accept a patch from you. It's not that hard to change. Otherwise I'll get to it later today...
https://github.com/brunobowden/j2objc-gradle/blob/master/j2objc.gradle#L482

**Comment by brunobowden** [comment]
You can now fix it with the latest version and following config:

j2objcConfig {
    cycleFinder true
    cycleFinderExpectedCycles 1
}

**Comment by confile** [comment]
LGTM
