### ISSUE TITLE
Convert to a buildable Gradle plugin

### ISSUE THREAD

**Issue by advayDev1** [brunobowden/j2objc-gradle#55]
It's pretty easy to do, and I can do it - but do y'all want that?
It is slightly more annoying to rapidly develop, but if it is a plugin you'll be able to jar it up and put it on the buildscript classpath of your actual java projects without having to hackily 'apply from'.

I have a number of other locally developed plugins in my toolchain for my main project; I put the plugin projects in both my gradle buildSrc project and as a peer to my regular Java code.  That allows them to get built on each gradle run (if anything has changed) while still getting the benefits of being a real plugin.

**Comment by confile** [comment]
I agree but first get all things more stable.

**Comment by advayDev1** [comment]
SG.

**Comment by confile** [comment]
@advayDev1 What is SG?

**Comment by brunobowden** [comment]
Sounds Good

**Comment by advayDev1** [comment]
sounds good.

apologies, old code review/bug commenting die hard.

**Comment by advayDev1** [comment]
per discussion splitting this into 2 issues.  assigning this one to myself, and creating a new plugin for the ability to package and publish as a plugin, to @brunobowden

**Comment by brunobowden** [comment]
Fair point. Please go ahead and make the split.
