### ISSUE TITLE
gradle j2objcTranslate Task Configuration

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#7]
I tried to add the realtime-json lib to J2Objc https://github.com/goodow/realtime-json
realtime-json-0.5.5-SNAPSHOT-sources.jar is under ${projectDir}/lib/

Here is my build.gradle config:

j2objcConfig {
 j2objcHome "/Applications/J2Objc/j2objc-0.9.6" 
 destDir "${projectDir}/../number-incrementer-ios/Classes"

translateFlags "--no-package-directories --prefixes prefixes.properties --mapping method-mappings.properties -use-arc -classpath ${projectDir}/lib/realtime-json-0.5.5-SNAPSHOT-sources.jar"

compileFlags "-ObjC -ljre_emul"

translateJ2objcLibs "guava-14.0.1.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"

filenameCollisionCheck = true
    testExecutedCheck = false
}

Running translation: 

```
gradle j2objcTranslate
```

Leats to the following errors: 

```
error: /Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/src/main/java/com/example/incrementer/shared/JSNIExample.java:3: The import com.goodow.realtime.json.JsonObject cannot be resolved
error: /Users/mg/Documents/Grails/GGTS3.6.2/TestJ2Objc/src/main/java/com/example/incrementer/shared/JSNIExample.java:14: JsonObject cannot be resolved to a type
```

This looks like my configuration is wrong. 

Given an external library ``mylib-source.jar`` 

What is the minimal configuration needed to make this lib working with ``gradle j2objcTranslate``?

**Comment by confile** [comment]
Okay I used javac first and found the error a lib was missing: 

```
translateFlags "--no-package-directories --prefixes prefixes.properties --mapping method-mappings.properties -use-arc -classpath ${projectDir}/lib/realtime-json-0.5.5-SNAPSHOT-sources.jar:${projectDir}/lib/realtime-json-0.5.5-SNAPSHOT.jar"
```

Is is possible to split the translateFlags over more than one line?

**Comment by brunobowden** [comment]
The answer is only a Google search away ;-)

http://mrhaki.blogspot.com/2010/11/groovy-goodness-string-continuation.html

**Comment by confile** [comment]
Thank you. Is there a way to set the classpath lib from dependencies section. For example if you have: 

```
dependencies {
   compile 'com.google.dagger:dagger:2.0-SNAPSHOT'
}  
```

do I have to link to the local jar file or is there any shortcut?

**Comment by confile** [comment]
I tried this: 

```
translateFlags "--no-package-directories --prefixes prefixes.properties --mapping method-mappings.properties -use-arc\
		-classpath ${projectDir}/lib/realtime-json-0.5.5-SNAPSHOT-sources.jar: ${projectDir}/lib/realtime-json-0.5.5-SNAPSHOT.jar"
```
but it did not work so I switched to the """ notation for multi row Strings.

**Comment by confile** [comment]
Fixed now.
