### ISSUE TITLE
Fix --build-closure performance exception

### ISSUE THREAD

**Issue by advayDev1** [brunobowden/j2objc-gradle#70]
I disagree that we should prioritize speed over correctness in the case below (my projects use --build-closure).  What are folks opinions' on me getting rid of this conditional and always keeping --build-closure if the user asked for it?  @confile  @brunobowden 

If we later find a way to make this work in all cases, we should make the optimization, but I don't think we should unless it is guaranteed correct.

```
...
        // add java classpath base to classpath for incremental translation
        // we have to check if translation has been done before or not
        // if it is only an incremental build we must remove the --build-closure
        // argument to make fewer translations of dependent classes 
        // NOTE: TODO there is one case which fails, when you have translated the code
        // make an incremental change which refers to a not yet translated class from a 
        // source lib. In this case due to not using --build-closure the dependent source 
        // we not be translated, this can be fixed with a clean and fresh build
        def translateFlags = "${project.j2objcConfig.translateFlags}"
        if (translatedFiles > 0) {
            translateFlags = translateFlags.toString().replaceFirst("--build-closure","").trim()
        }
...
```

**Comment by brunobowden** [comment]
I'm generally inclined to make sure that builds work correctly and are repeatable and then have speed be secondary item. I don't understand this particular issue well enough to make a judgement call.

**Comment by advayDev1** [comment]
@brunobowden the issue is that it is very difficult (without reimplementing a lot of j2objc's internal logic) to implement incremental translation with --build-closure at all.  With --build-closure, j2objc can choose - as it deems necessary - to translate files on your sourcepath that are not passed as files for translation to j2objc.   Two (non-exhaustive) possibilities where this occurs:
- this project's java source file (A.java) depends on other java source (external/B.java) (in another project or in a source jar, but not in the core j2objc jars): Both A.java and external/B.java must be translated by j2objc.  With 'j2objc --build-closure A.java', both A.h|m and external/B.h|m will be (re)generated.  The first time A.java adds a dependency to external/B.java this is sufficient and necessary.  Later time it is not necessary to regenerate external/B.java, but this is difficult to detect.  (so: fast to never keep --build-closure, correct to always keep --build-closure).
- this project's java source file that was modified (A.java) since last translation depends on another java source (B.java) in the same project that was *not* modified.  With 'j2objc --build-closure A.java', a modification to A.java will also cause the retranslation of B.java.  I assume this snippet of code was meant to speed up this common case by doing just 'j2objc A.java' which won't retranslate B.java.  (again: fast to never keep --build-closure, correct to always keep --build-closure).

I'd still go with always correct: always keep --build-closure.

**Comment by brunobowden** [comment]
Advay, it would be great if we could discuss this in person, it'll help me
to better understand the issue. If you need a stop gap for now, then just
add a flag.

**Comment by advayDev1** [comment]
Agreed per meeting with @brunobowden and @confile: We'll revert this change, but with a flag to *if you know what you are doing* still remove build closure.
