### ISSUE TITLE
Sort authors be Lastname

### ISSUE THREAD

**Issue by confile** [brunobowden/j2objc-gradle#71]
I guess the authors should be sorted by last name instead of firstname?

https://github.com/brunobowden/j2objc-gradle/blob/master/AUTHORS#L1

**Comment by brunobowden** [comment]
Django sorts by first name:
https://github.com/django/django/blob/master/AUTHORS

OpenStack Swift sorts by last name:
https://github.com/openstack/swift/blob/master/AUTHORS

I tried looking for some reference on the preferred way to do it for GitHub
and couldn't find it. I think this just comes down to a personal preference.

**Comment by confile** [comment]
From articles I published at University I remember always by last name.

**Comment by brunobowden** [comment]
I personally prefer first name. If there was some published convention
about this, particularly for GitHub, then I'd follow that.

**Comment by confile** [comment]
Okay then lets stay with that.
