### ISSUE TITLE
Gradle projects lacking sourceSets will not compile

### ISSUE THREAD

**Issue by advayDev1** [brunobowden/j2objc-gradle#75]
We've assumed Java plugin (and its derivatives, like Groovy plugin) usage, which for example use sourceSets.  Where we use Java plugin convention by default, we should provide a way to skip that default by providing flags.

As reported by @maxbritto in #48.

At minimum we should allow overriding of the java, test, and resource source directories.

**Comment by advayDev1** [comment]
@brunobowden , some important questions re: 'magic' configuration vs. breadth of support vs. complexity of code here:
- Do we want to support non-Java-plugin-derived projects at all?
  - Do we want to fail fast for non-Java plugins or provide lots of configurable flags?
  - This increases the test matrix substantially.  Somewhere the line should be drawn, perhaps at Ant builds, etc.
  - Either way, we need to detect and fail with proper messaging when projects fail our assumptions. 
- When the Java plugin assumptions fail, should we guess defaults or require explicit configuration and fail with an error unless they are provided?
  - In this case: When sourceSets are not provided, we could either default a java source directory flag to null and require an override, or assume $projectDir/src/main/java (for example).
  - Guessing defaults would be duplicative of functionality in the Java plugin, which sets up these conventions.

Thoughts?

**Comment by brunobowden** [comment]
My general purpose is to maximize the utility for a broad range of users.
So that for most to virtually all people that use the plugin, it works well
for them. That means covering the vast majority of common cases. I'm less
of a purist that just wanting it to work well. I'm not sure what the right
answer is... should we tell people to apply the java plugin... or
automatically create the sourceSets ourselves?

**Comment by advayDev1** [comment]
I think neither.  The java plugin simply may not apply to their usecase.
Making the source set  ourselves will mutate the project and may cause hard
to debug problems for the rest of the build.

If we want to support automatically a broad range I'd go with a flag that
defaults to the source set, backs off to src/main/java and remains
configurable.  As long as you're OK with the larger test matrix.

**Comment by brunobowden** [comment]
That sounds a reasonable trade off. I'd like to work towards adding more
testing for this as well.

**Comment by advayDev1** [comment]
Ok see pull #78
