### ISSUE TITLE
Issues with J2objcXcodeTask

### ISSUE THREAD

**Issue by MohammadHejazi** [brunobowden/j2objc-gradle#79]
Thank you for creating this plugin. Just some notes/issues:

1. The `srcDir` for this task should be `j2objcConfig.destDir` not `${buildDir}/j2objc`.
2. What is the parameter `-p` for? I can't find it here `https://github.com/developertown/integratej2objc`.
3. The source directory `-s` should be relative to `j2objcConfig.xcodeProjectDir`.
4. The parameter `-g` is the group path inside Xcode project, not a directory as this name suggests `xcodeJ2objcGeneratedDir`.

**Comment by brunobowden** [comment]
@jonnolen is the best person to give feedback on this since he developed this area of the plugin

**Comment by brunobowden** [comment]
We've deprecated this part of the plugin and are now working on a new version that uses CocoaPods.
