### ISSUE TITLE
CocoaPods Library integration

### ISSUE THREAD

**Issue by brunobowden** [brunobowden/j2objc-gradle#96]
Instead of including source code, switch to linking a prebuilt library and including the library headers.
1) include j2objc-generated-library.a
2) add j2objc headers folder to HEADER_SEARCH_PATH
3) update PROJECT-bridgingheader.h to reference the all the headers within Swift, as defined by an "export interface" sourceSet

@confile - make the changes to output the correct file and then reassign this to...
@advayDev1 - so he can modify the file with the correct output

**Comment by confile** [comment]
@brunobowden Shouldn't `` j2objc-generated-library.a`` be something like  ``j2objc-generated-projectName-library.a``?

to 3): There is no ``PROJECT-bridgingheader.h`. With pods we can only have one bridging header per target and this one should not be in a pod.

**Comment by confile** [comment]
@brunobowden By 

> j2objc headers

you mean ``${project.buildDir}/j2objc``right?

**Comment by confile** [comment]
@brunobowden 

> j2objc headers folder

means ``${project.buildDir}/j2objc`` right?

**Comment by brunobowden** [comment]
@Confile - talking with @advayDev1, we settled on "projectName-j2objc.a", for the headers, we may yet move them around. So don't worry about further changes for now. Thanks for what you've fixed already.
